// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wba.EFbasics.Web.Data;

#nullable disable

namespace Wba.EFbasics.Web.Migrations
{
    [DbContext(typeof(HorseDbContext))]
    [Migration("20251120103141_AddHorseImage")]
    partial class AddHorseImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContestHorse", b =>
                {
                    b.Property<int>("ContestsId")
                        .HasColumnType("int");

                    b.Property<int>("HorsesId")
                        .HasColumnType("int");

                    b.HasKey("ContestsId", "HorsesId");

                    b.HasIndex("HorsesId");

                    b.ToTable("ContestHorse");

                    b.HasData(
                        new
                        {
                            ContestsId = 1,
                            HorsesId = 1
                        },
                        new
                        {
                            ContestsId = 1,
                            HorsesId = 2
                        },
                        new
                        {
                            ContestsId = 1,
                            HorsesId = 3
                        },
                        new
                        {
                            ContestsId = 2,
                            HorsesId = 1
                        },
                        new
                        {
                            ContestsId = 2,
                            HorsesId = 2
                        },
                        new
                        {
                            ContestsId = 2,
                            HorsesId = 3
                        });
                });

            modelBuilder.Entity("Wba.EFbasics.Core.Entities.Contest", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 12.2m,
                            Location = "kortestraat 56, Poperinge",
                            Name = "Poperingse Regatta"
                        },
                        new
                        {
                            Id = 2,
                            Distance = 8.2m,
                            Location = "Langestraat 12, Veurne",
                            Name = "Veurnse Pannenkoekenrace"
                        });
                });

            modelBuilder.Entity("Wba.EFbasics.Core.Entities.Horse", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFilename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationId")
                        .IsUnique();

                    b.HasIndex("RaceId");

                    b.ToTable("Horses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Belgium",
                            DateOfBirth = new DateTime(1975, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentificationId = 1,
                            Name = "Mighty Mouse",
                            RaceId = 1,
                            Weight = 250.3m
                        },
                        new
                        {
                            Id = 2,
                            Country = "Italy",
                            DateOfBirth = new DateTime(2022, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentificationId = 2,
                            Name = "Superbad",
                            RaceId = 2,
                            Weight = 200.3m
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            DateOfBirth = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentificationId = 3,
                            Name = "StrudelWasser",
                            RaceId = 3,
                            Weight = 260.3m
                        });
                });

            modelBuilder.Entity("Wba.EFbasics.Core.Entities.Identification", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("IdentificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Identifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdentificationCode = "Alfa56"
                        },
                        new
                        {
                            Id = 2,
                            IdentificationCode = "Tango95"
                        },
                        new
                        {
                            Id = 3,
                            IdentificationCode = "Papa44"
                        });
                });

            modelBuilder.Entity("Wba.EFbasics.Core.Entities.Race", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arabian FullBlood"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brabants FarmerHorse"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Schoorse Shetlander Pony"
                        });
                });

            modelBuilder.Entity("ContestHorse", b =>
                {
                    b.HasOne("Wba.EFbasics.Core.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wba.EFbasics.Core.Entities.Horse", null)
                        .WithMany()
                        .HasForeignKey("HorsesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wba.EFbasics.Core.Entities.Horse", b =>
                {
                    b.HasOne("Wba.EFbasics.Core.Entities.Identification", "Identification")
                        .WithOne("Horse")
                        .HasForeignKey("Wba.EFbasics.Core.Entities.Horse", "IdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wba.EFbasics.Core.Entities.Race", "Race")
                        .WithMany("Horses")
                        .HasForeignKey("RaceId");

                    b.Navigation("Identification");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Wba.EFbasics.Core.Entities.Identification", b =>
                {
                    b.Navigation("Horse");
                });

            modelBuilder.Entity("Wba.EFbasics.Core.Entities.Race", b =>
                {
                    b.Navigation("Horses");
                });
#pragma warning restore 612, 618
        }
    }
}
